# Kafka Configuration
kafka.bootstrap.servers=13.209.157.53:9092,15.164.111.153:9092,3.34.32.69:9092
kafka.source.topic=test-topic
kafka.sink.topic=sales_total_realtime
kafka.consumer.group=sales-total-group

# Schema Registry Configuration
schema.registry.url=http://43.201.175.172:8081,http://43.202.127.159:8081

# Flink Configuration
flink.parallelism=1
flink.checkpoint.interval=60000


# Job Configuration
flink.job.name=Sales Total Realtime

# Application Configuration
app.timezone=Asia/Seoul
